name: "Design and develop a software product"
description: "A workflow for designing and developing a software product."

tasks:
  chief_product_officer:
    generator: openai://gpt-4o

  chief_technology_officer:
    generator: anthropic://claude

  manager:
    generator: anthropic://claude

report: >
  # Product Requirements for $product

  $requirements

  # Technologies

  $tech_stack

  # Tasks

  $tasks
